# name of the software
name: Diabet
# current version of the software
version: 1.1.0

# list of additional links on the right of the top menu
headerLinks:
  - title: Главная
    url: /
  - title: Обо Мне
    url: /обо-мне
  - title: Услуги
    url: /услуги
  - title: Мои Статьи
    url: /мои-статьи
  - title: Полезная Информация
    url: /полезная-информация
  - title: Знаете Ли Вы Что
    url: /знаете-ли-вы-что

excerpt_separator: <!--more-->

# google analytics
analytics:
  account:
  domain:

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

# gems:
#   - jekyll-mentions
#   - jemoji
#   - jekyll-redirect-from
#   - jekyll-sitemap
